// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnPp13WO8ksWBWY5K56QzBU7C1jEIL4J0',
    appId: '1:13205323047:web:aeb7ab63716ca756353d02',
    messagingSenderId: '13205323047',
    projectId: 'insta-proj-b47b8',
    authDomain: 'insta-proj-b47b8.firebaseapp.com',
    storageBucket: 'insta-proj-b47b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6_ALrqX66JS_2s8lsnabMLci5wUu3hQs',
    appId: '1:13205323047:android:e9f9eeb0e10ef85e353d02',
    messagingSenderId: '13205323047',
    projectId: 'insta-proj-b47b8',
    storageBucket: 'insta-proj-b47b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Rr0qYzqMjN6p6jV4WkB_vfbGHWfbc-A',
    appId: '1:13205323047:ios:3221e543f5c30f3e353d02',
    messagingSenderId: '13205323047',
    projectId: 'insta-proj-b47b8',
    storageBucket: 'insta-proj-b47b8.appspot.com',
    iosClientId: '13205323047-bp1vt566bgrj4cbs260pv37i8bu2qhn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.instgramProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Rr0qYzqMjN6p6jV4WkB_vfbGHWfbc-A',
    appId: '1:13205323047:ios:79488cc6f8519a7f353d02',
    messagingSenderId: '13205323047',
    projectId: 'insta-proj-b47b8',
    storageBucket: 'insta-proj-b47b8.appspot.com',
    iosClientId: '13205323047-5fsb90t84sqhep7gs6k3s6dsg932ju1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.instgramProject.RunnerTests',
  );
}
